### PR TITLE
GitHub greg branch

### PR DESCRIPTION
**Pull request by kosinovsky**

### CODE REVIEW

**Comment by adammoody** [comment]
Thanks, @kosinovsky .  Note that the ER functions may not return the same return code on all processes.  For some of these tests, I think we'd want to flag a problem if any process finds an error, e.g. all ranks return ER_SUCCESS except for one.  You could use an MPI_Allreduce across the return codes to do that.

Also, I see you have a couple tests that look for ER_FAILURE on the rebuild_one_failure_reverse case.  It's been a while since I looked at the ER code, but that is surprising to me.  I think we should return ER_FAILURE on a process only if something failed to work.  Can you look into that?

**Comment by adammoody** [comment]
Oh, let's add a check that ER_Create succeeds, too.  I think it returns -1 on error, but check the code.

**Comment by kosinovsky** [comment]
Hi Adam.
Yes, I sent you the email on Monday regarding the failures returned by ER_Dispatch and ER_Wait when called from test_rebuild_one_failure_reverse.
I convinced myself that it was probably as expected because in that test we delete the files for one of the processes and (for example) in ER_Dispatch dispatch there is this code:
  if (set) {
    /* check that we're in the right state */
    if (set->api_state != ER_API_STATE_CREATED) {
      /* wrong state */
      er_err("ER_Dispatch called in wrong order");
      return ER_FAILURE;
    }
I was sure that it was triggering that failure. However, I did not check that. I will do that now.

Thank you,
Greg

**Comment by kosinovsky** [comment]
Hi Adam.
In test_rebuild_one_failure_reverse function,
The ER_Dispatch failure occurs on line 680 in er.c:
rc = er_rebuild(comm_world, comm_store, path);
inside er_rebuild, the failure occurs on line 523 – the er_state_read() call does not return ER_STATE_ENCODED in the “state” parameter.

Is that a correct behavior?

Thank you,
Greg

From: Kosinovsky, Greg
Sent: Thursday, August 22, 2019 11:26 AM
To: ECP-VeloC/er <reply@reply.github.com>
Subject: RE: [ECP-VeloC/er] GitHub greg branch (#1)

Hi Adam.
Yes, I sent you the email on Monday regarding the failures returned by ER_Dispatch and ER_Wait when called from test_rebuild_one_failure_reverse.
I convinced myself that it was probably as expected because in that test we delete the files for one of the processes and (for example) in ER_Dispatch dispatch there is this code:
  if (set) {
    /* check that we're in the right state */
    if (set->api_state != ER_API_STATE_CREATED) {
      /* wrong state */
      er_err("ER_Dispatch called in wrong order");
      return ER_FAILURE;
    }
I was sure that it was triggering that failure. However, I did not check that. I will do that now.

Thank you,
Greg

**Comment by adammoody** [comment]
Oh, how are you running the test?  Like redset, this uses hostname to set up failure groups, and I think it uses XOR or PARTNER so that you'd need multiple nodes to actually have the test work.  Are you running on multiple hosts, or just one?

Assuming you're just running on one host and assuming it is actually trying to use XOR or PARTNER on redset, we should have probably thrown an error when we created the scheme or tried to use it for encoding.

Go ahead and test that ER_Create_Scheme returns something other than -1.  Looks like we should also modify ER_Create and ER_Free and maybe others to return an error if scheme_id < 0.

**Comment by adammoody** [comment]
@kosinovsky , found this outstanding PR.  Is this still valid or should we close it out?

**Comment by kosinovsky** [comment]
Yeah, that was just me needing an explanation. We can close it.
Thank you,
Greg

**Pull request closed without merging**
